services:
  - type: web
    name: builduo-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --host=0.0.0.0 --port=$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    numInstances: 1
    region: oregon  # or choose the closest region to your audience
    env: 
      - key: TZ
        value: "Asia/Kolkata"
